### ISSUE TITLE
Allow <somevalue> and <novalue> to be added via QuickStatements

### ISSUE THREAD

**Issue by ChristianKleineidam** [magnusmanske/quickstatements#10]
Currently, given the lack of an ability to add <somevalue> via quickstatement Q53569537 has to be used which then creates extra edits to be replaced by <somevalue>. It would be great if QuickStatements would support <somevalue> directly. The same goes for <novalue>.

The implementation of this currently holds back the RfC https://www.wikidata.org/wiki/Wikidata:Requests_for_comment/Cleaning_up_the_ontology_of_anonymous#Discussion

**Comment by ChristianKleineidam** [comment]
At the RfC SixTwoEight suggest to fix this:

> Clone https://github.com/magnusmanske/quickstatements, do <code>curl https://www.wikidata.org/wiki/User:SixTwoEight/QS_fix?action=raw > 628fix.patch && git am < 628fix.patch</code>, and you'll be running the fixed version (<code>git am</code> will add it as a commit to the current branch).

**Comment by magnusmanske** [comment]
Patch applied, thanks!
