### ISSUE TITLE
CSV item creation is broken if statements are being added

### ISSUE THREAD

**Issue by mahir256** [magnusmanske/quickstatements#38]
When I try to import commands to create new items with the CSV syntax, and those items have a statement, such as
`qid,Lko,Len,P1343`
`,"해요체","polite style",Q115683766`
the following HTML appears in the API response immediately prior to the JSON output:
`<br />`
`<b>Notice</b>:  Undefined index: new_statement in <b>/data/project/quickstatements/public_html/quickstatements.php</b> on line <b>640</b><br />`
Because of this extra output, the screen does not proceed to where I can start the resultant batch.
This error does not appear when trying to *add* statements in CSV syntax to existing items, and this error HTML appears in the API response each time a new statement is detected to be added--if there were two statement columns and two items being created in the above command sample, then the 'undefined index' error would appear four times.
My initial thought is that this has been broken since 8d516dea588e0b0ada237504ba927860f23ae440 but I am not entirely certain.

**Comment by PythonCoderAS** [comment]
I ran into the same issue.

**Comment by RichardNevell** [comment]
Me too. The tool's import V1 function still works for creating new items, but CSV import doesn't.

**Comment by MFTabriz** [comment]
This is a typical failure mode which should have been caught in automatic functionality tests. Do we have any CI tests for quickstatements?

**Comment by PythonCoderAS** [comment]
There are no tests lol
