### ISSUE TITLE
QuickStatements localization

### ISSUE THREAD

**Issue by Prasanta-Hembram** [magnusmanske/quickstatements#48]
Hi, may I know where the localization of QuickStatements tool is happening.

**Comment by hrabian** [comment]
https://tooltranslate.toolforge.org/#tool=24 (globe icon from QS page)

**Comment by Prasanta-Hembram** [comment]
Thank you @hrabian 💐💐

**Comment by Prasanta-Hembram** [comment]
sorry for replying in this closed PR. Is it possible to add  **[Santali](https://sat.wikipedia.org/wiki/%E1%B1%A2%E1%B1%A9%E1%B1%AC%E1%B1%A9%E1%B1%9B_%E1%B1%A5%E1%B1%9F%E1%B1%A6%E1%B1%B4%E1%B1%9F): "ᱥᱟᱱᱛᱟᱲᱤ"** to the list of languages in the below json file : https://tools.wmflabs.org/tooltranslate/data/languages.json

I'm unable to add Santali using [[+]](https://tooltranslate.toolforge.org/#) , it's says [undefined](https://tooltranslate.toolforge.org/#), adding language to the above json file may solve this issue.

Thanks

**Comment by magnusmanske** [comment]
Done, please try

**Comment by Prasanta-Hembram** [comment]
Thank you so much @magnusmanske 💐💐, it is working now.
