### ISSUE TITLE
QuickStatememt fails to handle P6375 (street address)

### ISSUE THREAD

**Issue by Ysogo** [magnusmanske/quickstatements#49]
It is not possible to add/change P6375 through quickstatement because it goes to error even with correct input statement.

Sample to test:
Q4115189|P6375|"Sunset Road"

My best guessing is that QS fails because Wikidata has a constrain to specificy the language code of the address for property P6375. To the best of my knowledge QS does not yet have a sintax to specifiy the language of a property value. Can someone implement it? A possible approach would be to specify the language code as a tail of the property code (e.g. P6375de for german)

**Comment by tuukka** [comment]
This works for me after I add the language code before the string like this:
```
Q4115189|P6375|en:"Sunset Road"
```
Result after running it: https://www.wikidata.org/w/index.php?title=Q4115189&diff=prev&oldid=1996982738

**Comment by Ysogo** [comment]
Thank you Tuukka. Now I understand what I did wrong.
