### ISSUE TITLE
Login link yields 403 error

### ISSUE THREAD

**Issue by pere-prlpz** [magnusmanske/quickstatements#55]
When clicking the log in link in QuickStatements https://quickstatements.toolforge.org/api.php?action=oauth_redirect it lands on a 403 Forbidden error page.

It is happening to me since yesterday. I tried different computers, different browses and different places,  with the same result.

OAuth for other tools seems to work fine - I checked Wikishootme and CropTool without any problem.

Maybe related: I think I had similar problems when logging in with QuickStatements in past weeks, but it solved itself in a few hours and I can't remember if I got a 403 error.

**Comment by magnusmanske** [comment]
Restarted webservice as php8.2 instead of 7.3, seems to work now.
